spring:
  application:
    name: "todo-list-security"
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active:
      - local
server:
  port: 8089
oauth:
  todo-list-api-secret: ${TODO_LIST_API_SECRET}
  todo-list-api-swagger-secret: ${TODO_LIST_API_SWAGGER_SECRET}
  todo-list-app-callback-url: ${TODO_LIST_APP_CALLBACK_URL}
  todo-list-api-swagger-callback-url: ${TODO_LIST_API_SWAGGER_CALLBACK_URL}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
debug: ${DEBUG}
logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL}
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/SECURITY?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true
    username: security
    password: security
    driver-class-name: com.mysql.cj.jdbc.Driver
oauth:
  todo-list-api-secret: dev-secret
  todo-list-api-swagger-secret: dev-secret
  todo-list-app-callback-url: http://localhost:3000/oauth-callback
  todo-list-api-swagger-callback-url: http://localhost:8088/webjars/springfox-swagger-ui/oauth2-redirect.html
cors:
  allowed-origins: http://localhost:3000,http://localhost:8088
debug: true
logging:
  level:
    org:
      springframework:
        security: DEBUG