spring:
  application:
    name: "todo-list-security"
  profiles:
    active:
      - local
server:
  port: 8089
logging:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
---
debug: true
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/SECURITY?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true
    username: security
    password: security
    driver-class-name: com.mysql.cj.jdbc.Driver