spring:
  application:
    name: "todo-list-api"
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active:
      - local
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=1m
server:
  port: 8088
  servlet:
    session:
      timeout: 30m

todolist:
  cors:
    origin: https://todolist-cyc-client.herokuapp.com
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/TODOLIST?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true
    username: todolist
    password: todolist
    driver-class-name: com.mysql.cj.jdbc.Driver

oauth:
  todo-list-api-secret: dev-secret
  todo-list-api-swagger-secret: dev-secret
  authentication-endpoint: http://localhost:8089/oauth/authorize
  get-token-endpoint: http://localhost:8089/oauth/token
  check-token-endpoint: http://localhost:8089/oauth/check_token

todolist:
  cors:
    origin: http://localhost:3000