spring:
  application:
    name: "todo-list-api"
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active:
      - local
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=1m
server:
  port: 8088
  servlet:
    session:
      timeout: 30m
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
---
spring:
  profiles: local
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/TODOLIST?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
todolist:
  cors:
    origin: http://localhost:3000