spring:
  application:
    name: "todo-list-api"
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active:
      - local
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=1m
oauth:
  client-id: todo-list-api

server:
  port: 8088
  servlet:
    session:
      timeout: 30m

todolist:
  cors:
    origin: https://todolist-cyc-client.herokuapp.com

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
---
debug: true
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/TODOLIST?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true
    username: todolist
    password: todolist
    driver-class-name: com.mysql.cj.jdbc.Driver

oauth:
  client-secret: dev-secret
  check-token-endpoint: http://localhost:8089/oauth/check_token

todolist:
  cors:
    origin: http://localhost:3000