CREATE DATABASE IF NOT EXISTS TODOLIST;

GRANT ALL PRIVILEGES ON *.* to 'user'@'%';
FLUSH PRIVILEGES;

USE TODOLIST;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS todos (
    id INTEGER AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    status TEXT NOT NULL,
    priority TEXT,
    description TEXT,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER AUTO_INCREMENT,
    role TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
)  ENGINE=INNODB;

INSERT INTO users (id, username, password)
VALUES (1, 'admin','$2a$10$JiHihK0nbeNPLBlqeXYgD.DaVW99FE1FMNl5EpN0CT4I5bFK9lzdC');

INSERT INTO roles (role, user_id)
VALUES ('A',1);