export const NEW_TODOS = 'NEW_TODOS';
export const LOAD_TODOS_REQUEST = 'LOAD_TODOS_REQUEST';
export const LOAD_TODOS_FAILURE = 'LOAD_TODOS_FAILURE';
export const NEW_ACTIVE_TODO = 'NEW_ACTIVE_TODO';
export const NEW_PAGING_INFO = 'NEW_PAGING_INFO';
export const SUBMIT_TODO_REQUEST = 'SUBMIT_TODO_REQUEST';
export const SUBMIT_TODO_FAILURE = 'SUBMIT_TODO_FAILURE';
export const SUBMIT_TODO_SUCCESS = 'SUBMIT_TODO_SUCCESS';
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';
export const RESET_ERROR_STATE = 'RESET_ERROR_STATE';


export const NEW_USERNAME = 'NEW_USERNAME';
export const ANONYMOUS_USERNAME = 'ANONYMOUS_USERNAME';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';